#import "./channelMessageFragment.gql"

fragment channelFragment on Channel {
  channelMessages { ...channelMessageFragment }
  channelType
  createdAt
  id
  lastMessage { ...channelMessageFragment }
  shipmentId
}
