#import "./customerOrganizationFragment.gql"

fragment shipperFragment on Shipper {
  # avatar { ...AttachmentFields }
  email
  emailNotifications
  hasUnreadNotifications
  id
  intercomToken
  language
  name
  organization { ...customerOrganizationFragment }
  phoneNumber
  status
}
